Assessment/urls.py
from django.urls import path
from . import views

app_name = 'Assessment'

urlpatterns = [
    path("ibigkas-menu/<uuid>/", views.mainPage, name="mainMenu"),

    path("", views.loginPage, name="login_page"),

    path("signIn", views.multiplayer_signIn, name="SignIn_multi"),
    path("create-account/", views.createAccount, name="createAccount"),
    
    # Assessment urls
    path("personality-test/<uuid>/", views.personalityTest, name="personality_test"),
    path("demographics/<uuid>/", views.demographicsQuestion, name="demographics"),

    path("pre-test/<uuid>/", views.pre_test, name="pre_test"),

    # AJAX URL PATH
    path("pre_test_ans/", views.pre_test_answer, name="pre_test_ans"),
    path("signIn_multi/", views.multi_signIn_ajax, name="multi_signIn"),
    path("demo_ansOne/", views.demographicsAnswerOne, name="demoOneAnswer"),
    path("demo_ansTwo/", views.demographicsAnswerTwo, name="demoTwoAnswer"),
    path("pre_assessment_ans/", views.personalityTestAnswer, name="preAnswer"),
    path("createAccoutAjax/", views.createAccountAjax, name="createAjax"),




]

ibigkas_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('jet/', include('jet.urls', 'jet')), 
    path('admin/', admin.site.urls),
    path('singleplayer/', include("singlePlayer.urls")),
    path('multiplayer/', include("revise_multiplayer.urls")),
    path('', include("Assessment.urls")),
]


admin.site.index_title = "Ibigkas"
admin.site.site_header = "Ibigkas Web Application Admin"
admin.site.site_title = "Ibigkas Admin"


# snake_case python 
# camelCase JS 
# kebab-case CSS  

Assessment/models.py
from ast import operator
from email.policy import default
from django.db import models

from revise_multiplayer.models import *
# Create your models here.
GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

OPERATOR_CHOICES = (
        ('+', 'Addition'),
        ('-', 'Subtraction'),
        ('×', 'Multiplication'),
        ('÷', 'Division'),
    )    

class ResearchStatus(models.Model):
    research_mode = models.BooleanField(default=True, verbose_name="Research Mode")

    @classmethod
    def object(cls):
        
        return cls._default_manager.all().first() # Since only one item

    def save(self, *args, **kwargs):
        self.pk = self.id = 1
        return super().save(*args, **kwargs)

    class Meta:
      verbose_name = "Research Mode"
      verbose_name_plural = "Research Mode"

    def __str_(self):
      return self.research_mode

class PersonalityTest(models.Model):
  id = models.AutoField(primary_key=True, verbose_name='Pre Assess ID')
  questions = models.CharField(max_length = 350, verbose_name='Questions')

  class Meta:
      verbose_name = "Personality Test"
      verbose_name_plural = "Personality Test"
  
  def __str_(self):
      return self.questions

class DemographicsModel(models.Model):
  question_part_one = models.CharField(max_length = 350, verbose_name='Questions I',blank=True, null=True,)
  question_part_one_tagalog = models.CharField(max_length = 350, verbose_name='Tagalog', blank=True, null=True,)
  
  class Meta:
      verbose_name = "Demographics Question I"
      verbose_name_plural = "Demographics Question I"

  def __str_(self):
      return self.question_part_one

class DemographicsTwoModel(models.Model):
  question_part_two = models.CharField(max_length = 350, verbose_name='Questions II',blank=True, null=True,)
  question_part_two_tagalog = models.CharField(max_length = 350, verbose_name='Tagalog', blank=True, null=True,)
  
  class Meta:
      verbose_name = "Demographics Question II"
      verbose_name_plural = "Demographics Question II"

  def __str_(self):
      return self.question_part_two


class PreTest(models.Model):
  operator = models.CharField(max_length = 50, choices=OPERATOR_CHOICES, verbose_name='Arithmetic Operators')
  q1 = models.CharField(max_length = 50, verbose_name='q1')
  q11 = models.CharField(max_length = 50, verbose_name='Optional', default=None, null=True, blank=True)

  q2 = models.CharField(max_length = 50, verbose_name='q2')
  q22 = models.CharField(max_length = 50, verbose_name='Optional', default=None, null=True, blank=True,)

  answer = models.CharField(max_length = 50, verbose_name='answer')

  def __str_(self):
      return self.q1

  class Meta:
      verbose_name = "Pre Test Question"



class Player(models.Model):
  uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

  username = models.CharField(max_length=250, verbose_name='Username', primary_key=True, unique=True)
  surname = models.CharField(max_length=250, verbose_name='Surname')
  gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
  age = models.PositiveIntegerField(verbose_name='Age')

  section = models.CharField(max_length=250, verbose_name='Section', blank=True, null=True)

  group =  models.ForeignKey(Group, on_delete=models.PROTECT, default=None, null=True, blank=True, help_text="Add Group for your student")
  user_session = models.CharField(max_length=150,verbose_name='User Session', null=True)
  # In-game fields 
  demographics =  models.TextField(verbose_name='Demographics', blank=True)
  personality_test =  models.TextField(verbose_name='Personality Test', blank=True)
  pre_test_answer = models.TextField(verbose_name='Pre-Test Answers', blank=True)
  pre_test_score = models.TextField(max_length=150,verbose_name='Pre-test Score', blank=True)
  is_complete_assessment = models.BooleanField(default=False)

  game_scores = models.TextField(verbose_name='Game Scores', blank=True)
  game_answer_history = models.TextField( verbose_name='Game Answers', blank=True)

  speed = models.CharField(max_length=250, verbose_name='Speed', null=True, blank=True)
  total_questions = models.CharField(max_length=250, verbose_name='Total Questions', null=True, blank=True)
  correct_answers = models.CharField(max_length=250, verbose_name='Correct Answers', null=True, blank=True)
  wrong_answers = models.CharField(max_length=250, verbose_name='Wrong Answers', null=True, blank=True)


  player_mode = models.CharField(max_length=250, verbose_name='Player Mode', null=True, blank=True)
  is_pending = models.BooleanField(default=True, verbose_name="Pending")

  date = models.DateField(auto_now_add=False, null=True)

  
  def __str__(self):
      return  self.username

  def clean(self):
      self.username = self.username.capitalize()
      self.surname = self.surname.capitalize()

Assessment/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from revise_multiplayer.models import *

class PersonalityTestForm(ModelForm):
	class Meta:
		model = PersonalityTest
		fields = ['questions']

class DemographicForm(ModelForm):
	class Meta:
		model = Player
		fields = ['demographics']
    
class createAccountForm(ModelForm):
	class Meta:
		model = Player
		fields = ['username', 'surname', 'section', 'gender']




# username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username', 'class':'form-control', 'id':'validationCustom01'}))
# email = forms.EmailField(max_length=50, help_text="Required. Add valid email address", label='Email : ',widget=forms.TextInput(attrs={'placeholder': 'Email', 'class':'form-control', 'id':'validationCustom03'}))

Assessment/views.py
from typing import NoReturn
from urllib.parse import parse_qs
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

# from Ibigkas.ibigkas_project.revise_multiplayer.views import room
from .models import *
from revise_multiplayer.models import *
from .forms import *

from django.contrib.sessions.models import Session
from django.contrib import messages

from datetime import datetime
import pytz
import json


def mainPage(request, uuid):
    # Creating user session and save to database
    user = Player.objects.get(uuid=uuid)
    group = user.group

    IST = pytz.timezone('Asia/Manila')
    datetime_ist = datetime.now(IST)
    date = datetime_ist.strftime('%Y-%m-%d')
    user.date = date

    session = request.session._get_or_create_session_key()
    user.user_session = session
    user.save()

    user_uuid = uuid
    request.session['uuid'] = user_uuid

    create_room_for_every_group(user)
    auto_assign_room_if_has_group(user, group)

    out = {
        "group": group
    }
    
    return render(request, "Assessment/main.html", out)

def personalityTest(request, uuid):
    #Saving uuid to session request to use on client side
    user_uuid = uuid
    request.session['uuid'] = user_uuid

    assessment = PersonalityTest.objects.all()
    
    out = {'assess': assessment}
    return render(request, "Assessment/assessment/personalityTest.html", out)

def demographicsQuestion(request, uuid):
    Player.objects.filter(uuid=uuid).update(player_mode="MultiPlayer")
    user = Player.objects.get(uuid=uuid)
    user_uuid = uuid
    request.session['uuid'] = user_uuid

    if user.demographics != '':
        if user.personality_test != '':
            # If all assessment is done, user will redirect at waiting area
            # REMINDER!! Please change the url path to waiting area.
            # Add condition to url path for pre test
            return redirect('revise_multiplayer:room_list', uuid=uuid)
        else:
          return redirect('Assessment:personality_test', uuid=uuid)
    else:
      demographics_question = DemographicsModel.objects.all()
      questionTwo = DemographicsTwoModel.objects.all()
      out = {'questionsOne': demographics_question,'questionTwo': questionTwo} 
      return render(request, "Assessment/assessment/Demographics.html", out)

def demographicsAnswerOne(request):
    if request.method == 'POST':
        studentAnsOne = request.POST['studentAnsOne']
        studentUUID = request.POST['studentUUID']
        Player.objects.filter(uuid=studentUUID).update(demographics=studentAnsOne)
        message = 'Pre assessment save'
        return HttpResponse(message)

def demographicsAnswerTwo(request):
    if request.method == 'POST':
        studentAnsTwo = request.POST['studentAnsTwo']
        studentUUID = request.POST['studentUUID']
        newAnswer = []

        models = Player.objects.filter(uuid=studentUUID).first()
        ans = models.demographics
        newAnswer.append(ans)
        newAnswer.append(studentAnsTwo)
        new_string = ''.join(str(x) for x in newAnswer)
        Player.objects.filter(uuid=studentUUID).update(demographics=new_string)

        out = {'stud_uuid': studentUUID}
        return JsonResponse(out)

#AJAX function to save student answer key on personality test database 
def personalityTestAnswer(request):
    if request.method == 'POST':
        studentAns1 = request.POST['studentAns']
        studentUUID = request.POST['studentUUID']
        Player.objects.filter(uuid=studentUUID).update(personality_test=studentAns1)
        message = 'Personality Test Save!'
        return HttpResponse(message)


def createAccountAjax(request):
    if request.method == 'POST':
        userName = request.POST['user_name']
        usersSurname = request.POST['users_surname']
        section = request.POST['section']
        gender = request.POST['user_gender']

        age = request.POST['user_age']
        age = int(age)

        userName = userName.capitalize()
        usersSurname = usersSurname.capitalize()
        section = section.capitalize()

        # Check if the user name is already use
        if Player.objects.filter(username=userName).exists():
            message = f'{userName} already exist. Please try another username'
            return HttpResponse(message)
        else:
            models = Player(username=userName, surname=usersSurname, age=age, gender=gender, section=section)
            models.save()
            user_uuid = models.uuid
            user_uuid = str(user_uuid)
            request.session['uuid'] = user_uuid
            message = user_uuid
            return HttpResponse(message)

def createAccount(request):
    try:
        session = request.session._get_or_create_session_key()
        user_key = Player.objects.get(user_session=session)
        if user_key.user_session != None:
            sessionTwo = request.session._get_or_create_session_key()
            user_key = Player.objects.get(user_session=sessionTwo)
            # if a user is already have a session id it will redirect to main menu urls. 
            return redirect('Assessment:mainMenu', uuid=user_key.uuid)
    except:
        session = None
        return render(request, "Assessment/createAccount.html")     

        

def loginPage(request):
    sample = ResearchStatus.objects.all()
    out = {
        "check":sample
    }
    return render(request,"Assessment/login.html", out)


def multiplayer_signIn(request):
    return render(request,"Assessment/signIn.html")

def multi_signIn_ajax(request):
    if request.method == 'POST':
        signIn_user = request.POST['signIn_user']
        signIn_user = signIn_user.capitalize()

        user_model =  Player.objects.filter(username=signIn_user)
        if user_model.exists():
            user_get_credentials = Player.objects.filter(username=signIn_user).first()
            credential_id = user_get_credentials.uuid
            out = {
                'credential': credential_id
            }
            return JsonResponse(out)
        else:
            message = "Please check your username!"

        return HttpResponse(message)

def pre_test(request, uuid):
    user_uuid = uuid
    request.session['uuid'] = user_uuid
    modelPretest = PreTest.objects.all()

    out = {
        "pretest": modelPretest
    }

    return render(request,"Assessment/PreTestAndPostTest/preTest.html", out)

def pre_test_answer(request):
    if request.method == 'POST':
        pretestAnswers = request.POST['pretestAnswers']
        pretestScore = request.POST['pretestScore']
        studentUUID = request.POST['studentUUID']
        Player.objects.filter(uuid=studentUUID).update(pre_test_score=pretestScore, pre_test_answer=pretestAnswers)


        message = "Nice"
        return HttpResponse(message)

# In every group there must be an uqual room name
def create_room_for_every_group(user):
    group_list = Group.objects.all()

    for i in range(len(group_list)):
        if not chk_has_room(group_list[i].name):
            new_room = Room.objects.create(
                room_name = group_list[i].name,
                group_name = group_list[i],
                password = "",
                is_research = True,
                # players = user.username if user.group == group_list[i] else "",
            )
            new_room.save()

def chk_has_room(group):
    room_list = Room.objects.all()
    for i in range(len(room_list)):
        if room_list[i].room_name == group:
            return True 
    return False

def auto_assign_room_if_has_group(user, group):
    # print("Group: " + group)
    if group != None:
        room = Room.objects.get(group_name=group)
        if user.username not in room.players:
            player_list = room.players
            player_list = player_list + ", " + user.username
            room.players= player_list
            room.save()
        

# Checks if in research mode
# ResearchStatus.object().research_mode

    

Assessment/templates/Assessment/createAccount.html
{% extends 'revise_multiplayer/multiPlayerBase.html' %}

{% block title %}Create Account{% endblock %}
{% load static %}
{% block content %}
<div class="create-container">
    
    <form method="POST" autocomplete="off" id="create-account">
        {% csrf_token %}
        <div class="cont">
            <h3>Create Account</h3>
            <input type="text" class="input" id="user" onkeyup="success()" name="username" placeholder="Enter username..." ><br>
            <input type="text" class="input" id="surnameId" onkeyup="success()" name="surname" placeholder="Enter surname..."><br>
            <input type="text" class="input" id="sectionId" onkeyup="success()" name="section" placeholder="Section..">
            
            <div class="gender-layout">
                <div class="gender">
                    <p>Gender</p>
                    <button id="male" type="button"  name="gender" value="M" class="btn btn-primary gen">Male</button>
                    <button id="female" type="button"  name="gender" value="F" class="btn btn-primary gen">Female</button>
                </div>
                <div class="birth">
                    <p>Enter your Age</p>
                    <input id="user_age"  class="inputTwo" placeholder="Age.." onkeyup="success()" type="number">
                </div>
            </div>
            <button type="submit" id="button" name="createAcc" class="btn btn-primary create-acc" disabled>create</button>
        </div>
    </form>
    <button onclick="back()" type="button" class="btn btn-primary host-game-back">back</button>
</div>
{% endblock %}

{% block scripts %}
{% for message in messages %}
        <script type="text/javascript">
          window.onload = function(){
            alert('{{message}}')
          }
        </script>
{% endfor %}

<script type="text/javascript">  
    // ================ CUSTOM GENDER BUTTON ==================
    var male = document.getElementById("male").addEventListener("click", changeText);
    var female = document.getElementById("female").addEventListener("click", changeText);  
    function changeText(event){
        const maleC = document.querySelector("#male");
        const femaleColor = document.querySelector("#female");

        if(event.target.id === "male"){
            // ADDING CLASS NAME "color"

            maleC.classList.toggle("color");
            // REMOVING CLASS NAME "color"
            femaleColor.classList.remove("color");
        }
        else if(event.target.id === "female"){
            // ADDING CLASS NAME "color"
            femaleColor.classList.toggle("color");
            // REMOVING CLASS NAME "color"
            maleC.classList.remove("color");            
        }
    }
    // ================END CUSTOM GENDER BUTTON==================


    function back(){
        let audio = new Audio("{% static 'Assessment/music/IBM_ui_Back.wav' %}");
        audio.play()
        setTimeout(function(){ 
        location.href='{% url "Assessment:login_page" %}';
        }, 400);
    }
    
    // DISABLE THE CREATE BUTTON IF THE INPUT IS EMPTY
    function success() {
	 if(document.getElementById("user").value==="" || document.getElementById("surnameId").value==="" || document.getElementById("sectionId").value==="" || document.getElementById("user_age").value==="") {   
        
        document.getElementById('button').disabled = true; 
        } else { 
            
            document.getElementById('button').disabled = false;
        }
    }

    $("#create-account").on("submit", function(e){
	e.preventDefault();
    
    var sam = document.getElementsByClassName('color')[0]?.value;
    const check_class= document.querySelector('.gen');
    if(check_class.classList.contains('color') === false && sam === 'F' || check_class.classList.contains('color') === true && sam === 'M') {
        
        var users_name = document.getElementById("user").value;
        var users_surname = document.getElementById("surnameId").value;
        var user_section = document.getElementById("sectionId").value;
        var user_age = document.getElementById("user_age").value;
        var user_gender = document.getElementsByClassName('color')[0].value;

        var url = '{% url "Assessment:createAjax" %}'
            $.ajax({
			type:'POST',
			url:url,
			data:{
                user_name: users_name,
                users_surname: users_surname,
                user_gender:user_gender,
                section:user_section,
                user_age:user_age,
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
			},
			success:function(data){
                var users_name = document.getElementById("user").value;
                // CONVERT THE FIRST LETTER OF THE 'uses_name' TO UPPER CASE THEN THE REST IS LOWER CASE
                function titleCase(string){
                    return string[0].toUpperCase() + string.slice(1).toLowerCase();
                }
                let result = titleCase(users_name);

                if(data === result +' already exist. Please try another username'){
                    alert(data)
                }else{
                    redirect_url = '/ibigkas-menu/'+data;
                    window.location.replace(redirect_url);
                }
                    
			},
            error : function () {
                alert("Error Ajax");
            }
		});
    }else{
        alert("Please choose your gender!")
    }
        
    });


</script>
{% endblock %}

Assessment/templates/Assessment/login.html
{% extends 'revise_multiplayer/multiPlayerBase.html' %} {% load static %} 
{% block title %}Ibigkas Login{% endblock %} {% block content %}
<div class="logIn_page">
  <img src="{% static 'Assessment/img/logo.png' %}" alt="ibigkas logo" />
  <div class="category">

    {% for i in check %}
        {% if i.research_mode %}
            <p>Mode: Research</p>
        {% endif %}
    {% endfor %} 

    <button type="button" id="sign" class="btn btn-primary">
      sign in
    </button>
    
    <button type="button" id="create" class="btn btn-primary">
      create account
    </button>
    
    <bgsound src="https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg">
  </div>
</div>
{% endblock %} {% block scripts %}
<script type="text/javascript">

  function playMusic(){
    let audio = new Audio("{% static 'Assessment/music/IBM_ui_Confirm.wav' %}");
    audio.play()
	}

  document.getElementById("sign").addEventListener("click", signIn);
  document.getElementById("create").addEventListener("click", create);

  function signIn() {
    playMusic()
    setTimeout(function(){ 
      location.href = '{% url "Assessment:SignIn_multi" %}';
     }, 400);
  }

  function create() {
    playMusic()
    setTimeout(function(){ 
      location.href = '{% url "Assessment:createAccount" %}';
     }, 400);
  }

</script>
{% endblock %}

Assessment/templates/Assessment/main.html
{% extends 'revise_multiplayer/multiPlayerBase.html' %}

{% block title %}Ibigkas Math{% endblock %}
{% load static %}
{% block content %}

<!-- sample -->
<div class="main-container-land">
    <img src="{% static 'Assessment/img/logo.png' %}" alt="ibigkas logo">
    <div class="btn-center">
        <button type="button" onclick="singlePlayer()" class="btn btn-primary">single player</button>
        <button type="button" onclick="multiplayer()" class="btn btn-primary">multiplayer</button>
        <button type="button" class="btn btn-primary">settings</button>
    </div>
</div>

{% endblock %}
{% block scripts %}
<script type="text/javascript">
    var group = "{{ group }}";
    var user_uuid= "{{ request.session.uuid }}";

    function playMusic(){
        let audio = new Audio("{% static 'Assessment/music/IBM_ui_Confirm.wav' %}");
        audio.play()
	}

    function singlePlayer(){
        playMusic()
        setTimeout(function(){ 
            window.location.replace('/singleplayer/menu-single-player/'+ user_uuid);
        }, 400);
    }

    function multiplayer(){
        if (group == "None"){
            playMusic()
            setTimeout(function(){ 
                window.location.replace('/demographics/' + user_uuid + "/");
            }, 400);
        }else{
             setTimeout(function(){ 
                window.location.replace('/multiplayer/room/'+ group + '/' + user_uuid + '/');
             }, 400);
        }
    }    
</script>
{% endblock %}

Assessment/templates/Assessment/signIn.html
{% extends 'revise_multiplayer/multiPlayerBase.html' %}
{% block title %}Sign In{% endblock %}
{% load static %}
{% block content %}
<div class="multi-sign-in logIn_page">
    <img src="{% static 'Assessment/img/logo.png' %}" alt="ibigkas logo">
    <form action="" autocomplete="off" id="login--form">
        {% csrf_token %}
        <div class="login-form-multi">
            <input type="text" id="sign-user" onkeyup="success() "name="username" placeholder="Enter username..." ><br>
            <button type="submit" id="button-signIn" name="signIn" class="btn btn-primary create-acc" disabled>sign in</button>
        </div>
    </form>
    <button onclick="back()" type="button" id="back" class="btn btn-primary host-game-back">back</button>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript"> 


     function success() {
        if(document.getElementById("sign-user").value==="") {   
            document.getElementById('button-signIn').disabled = true; 
        } else {    
            document.getElementById('button-signIn').disabled = false;
        }
    }

    var count = 1;

    $("#login--form").on("submit", function(e){
	e.preventDefault();
        var signIn_user = document.getElementById("sign-user").value;
        var url = '{% url "Assessment:multi_signIn" %}'
        $.ajax({
			type:'POST',
			url:url,
			data:{
                signIn_user: signIn_user,
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
			},
			success:function(data){
                
                if(data === "Please check your username!"){
                    if(count === 3){
                        alert("Please create new account!");
                         window.location.replace('/create-account/');
                    }else{
                        ++count;
                        alert("Please check your username!");
                    }
                }
                else{
                    let audio = new Audio("{% static 'Assessment/music/IBM_ui_Confirm.wav' %}");
                    audio.play()
                    setTimeout(function(){ 
                        redirect_url = '/ibigkas-menu/'+data.credential;
                        window.location.replace(redirect_url);
                    }, 400);
                }
                
			},
            error : function () {
                alert("Error Ajax");
            }
		});
    });

    function create(){
        location.href='{% url "Assessment:createAccount" %}';
    }


 
    function back(){
        let audio = new Audio("{% static 'Assessment/music/IBM_ui_Back.wav' %}");
        audio.play()
        setTimeout(function(){ 
           location.href='{% url "Assessment:login_page" %}';
        }, 400);
    }
    
</script>
{% endblock %}