Assessment/urls.py
from django.urls import path
from . import views

app_name = 'Assessment'

urlpatterns = [
    path("ibigkas-menu/<uuid>/", views.mainPage, name="mainMenu"),

    path("", views.loginPage, name="login_page"),

    path("signIn", views.multiplayer_signIn, name="SignIn_multi"),
    path("create-account/", views.createAccount, name="createAccount"),
    
    # Assessment urls
    path("personality-test/<uuid>/", views.personalityTest, name="personality_test"),
    path("demographics/<uuid>/", views.demographicsQuestion, name="demographics"),

    path("pre-test/<uuid>/", views.pre_test, name="pre_test"),

    # AJAX URL PATH
    path("pre_test_ans/", views.pre_test_answer, name="pre_test_ans"),
    path("signIn_multi/", views.multi_signIn_ajax, name="multi_signIn"),
    path("demo_ansOne/", views.demographicsAnswerOne, name="demoOneAnswer"),
    path("demo_ansTwo/", views.demographicsAnswerTwo, name="demoTwoAnswer"),
    path("pre_assessment_ans/", views.personalityTestAnswer, name="preAnswer"),
    path("createAccoutAjax/", views.createAccountAjax, name="createAjax"),




]

ibigkas_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('jet/', include('jet.urls', 'jet')), 
    path('admin/', admin.site.urls),
    path('singleplayer/', include("singlePlayer.urls")),
    path('multiplayer/', include("revise_multiplayer.urls")),
    path('', include("Assessment.urls")),
]


admin.site.index_title = "Ibigkas"
admin.site.site_header = "Ibigkas Web Application Admin"
admin.site.site_title = "Ibigkas Admin"


# snake_case python 
# camelCase JS 
# kebab-case CSS  

Assessment/models.py
from ast import operator
from email.policy import default
from django.db import models

from revise_multiplayer.models import *
# Create your models here.
GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

OPERATOR_CHOICES = (
        ('+', 'Addition'),
        ('-', 'Subtraction'),
        ('×', 'Multiplication'),
        ('÷', 'Division'),
    )    

class ResearchStatus(models.Model):
    research_mode = models.BooleanField(default=True, verbose_name="Research Mode")

    @classmethod
    def object(cls):
        
        return cls._default_manager.all().first() # Since only one item

    def save(self, *args, **kwargs):
        self.pk = self.id = 1
        return super().save(*args, **kwargs)

    class Meta:
      verbose_name = "Research Mode"
      verbose_name_plural = "Research Mode"

    def __str_(self):
      return self.research_mode

class PersonalityTest(models.Model):
  id = models.AutoField(primary_key=True, verbose_name='Pre Assess ID')
  questions = models.CharField(max_length = 350, verbose_name='Questions')

  class Meta:
      verbose_name = "Personality Test"
      verbose_name_plural = "Personality Test"
  
  def __str_(self):
      return self.questions

class DemographicsModel(models.Model):
  question_part_one = models.CharField(max_length = 350, verbose_name='Questions I',blank=True, null=True,)
  question_part_one_tagalog = models.CharField(max_length = 350, verbose_name='Tagalog', blank=True, null=True,)
  
  class Meta:
      verbose_name = "Demographics Question I"
      verbose_name_plural = "Demographics Question I"

  def __str_(self):
      return self.question_part_one

class DemographicsTwoModel(models.Model):
  question_part_two = models.CharField(max_length = 350, verbose_name='Questions II',blank=True, null=True,)
  question_part_two_tagalog = models.CharField(max_length = 350, verbose_name='Tagalog', blank=True, null=True,)
  
  class Meta:
      verbose_name = "Demographics Question II"
      verbose_name_plural = "Demographics Question II"

  def __str_(self):
      return self.question_part_two


class PreTest(models.Model):
  operator = models.CharField(max_length = 50, choices=OPERATOR_CHOICES, verbose_name='Arithmetic Operators')
  q1 = models.CharField(max_length = 50, verbose_name='q1')
  q11 = models.CharField(max_length = 50, verbose_name='Optional', default=None, null=True, blank=True)

  q2 = models.CharField(max_length = 50, verbose_name='q2')
  q22 = models.CharField(max_length = 50, verbose_name='Optional', default=None, null=True, blank=True,)

  answer = models.CharField(max_length = 50, verbose_name='answer')

  def __str_(self):
      return self.q1

  class Meta:
      verbose_name = "Pre Test Question"



class Player(models.Model):
  uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

  username = models.CharField(max_length=250, verbose_name='Username', primary_key=True, unique=True)
  surname = models.CharField(max_length=250, verbose_name='Surname')
  gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
  age = models.PositiveIntegerField(verbose_name='Age')

  section = models.CharField(max_length=250, verbose_name='Section', blank=True, null=True)

  group =  models.ForeignKey(Group, on_delete=models.PROTECT, default=None, null=True, blank=True, help_text="Add Group for your student")
  user_session = models.CharField(max_length=150,verbose_name='User Session', null=True)
  # In-game fields 
  demographics =  models.TextField(verbose_name='Demographics', blank=True)
  personality_test =  models.TextField(verbose_name='Personality Test', blank=True)
  pre_test_answer = models.TextField(verbose_name='Pre-Test Answers', blank=True)
  pre_test_score = models.TextField(max_length=150,verbose_name='Pre-test Score', blank=True)
  is_complete_assessment = models.BooleanField(default=False)

  game_scores = models.TextField(verbose_name='Game Scores', blank=True)
  game_answer_history = models.TextField( verbose_name='Game Answers', blank=True)

  speed = models.CharField(max_length=250, verbose_name='Speed', null=True, blank=True)
  total_questions = models.CharField(max_length=250, verbose_name='Total Questions', null=True, blank=True)
  correct_answers = models.CharField(max_length=250, verbose_name='Correct Answers', null=True, blank=True)
  wrong_answers = models.CharField(max_length=250, verbose_name='Wrong Answers', null=True, blank=True)


  player_mode = models.CharField(max_length=250, verbose_name='Player Mode', null=True, blank=True)
  is_pending = models.BooleanField(default=True, verbose_name="Pending")

  date = models.DateField(auto_now_add=False, null=True)

  
  def __str__(self):
      return  self.username

  def clean(self):
      self.username = self.username.capitalize()
      self.surname = self.surname.capitalize()

Assessment/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from revise_multiplayer.models import *

class PersonalityTestForm(ModelForm):
	class Meta:
		model = PersonalityTest
		fields = ['questions']

class DemographicForm(ModelForm):
	class Meta:
		model = Player
		fields = ['demographics']
    
class createAccountForm(ModelForm):
	class Meta:
		model = Player
		fields = ['username', 'surname', 'section', 'gender']




# username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username', 'class':'form-control', 'id':'validationCustom01'}))
# email = forms.EmailField(max_length=50, help_text="Required. Add valid email address", label='Email : ',widget=forms.TextInput(attrs={'placeholder': 'Email', 'class':'form-control', 'id':'validationCustom03'}))

Assessment/views.py
from typing import NoReturn
from urllib.parse import parse_qs
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

# from Ibigkas.ibigkas_project.revise_multiplayer.views import room
from .models import *
from revise_multiplayer.models import *
from .forms import *

from django.contrib.sessions.models import Session
from django.contrib import messages

from datetime import datetime
import pytz
import json


def mainPage(request, uuid):
    # Creating user session and save to database
    user = Player.objects.get(uuid=uuid)
    group = user.group

    IST = pytz.timezone('Asia/Manila')
    datetime_ist = datetime.now(IST)
    date = datetime_ist.strftime('%Y-%m-%d')
    user.date = date

    session = request.session._get_or_create_session_key()
    user.user_session = session
    user.save()

    user_uuid = uuid
    request.session['uuid'] = user_uuid

    create_room_for_every_group(user)
    auto_assign_room_if_has_group(user, group)

    out = {
        "group": group
    }
    
    return render(request, "Assessment/main.html", out)

def personalityTest(request, uuid):
    #Saving uuid to session request to use on client side
    user_uuid = uuid
    request.session['uuid'] = user_uuid

    assessment = PersonalityTest.objects.all()
    
    out = {'assess': assessment}
    return render(request, "Assessment/assessment/personalityTest.html", out)

def demographicsQuestion(request, uuid):
    Player.objects.filter(uuid=uuid).update(player_mode="MultiPlayer")
    user = Player.objects.get(uuid=uuid)
    user_uuid = uuid
    request.session['uuid'] = user_uuid

    if user.demographics != '':
        if user.personality_test != '':
            # If all assessment is done, user will redirect at waiting area
            # REMINDER!! Please change the url path to waiting area.
            # Add condition to url path for pre test
            return redirect('revise_multiplayer:room_list', uuid=uuid)
        else:
          return redirect('Assessment:personality_test', uuid=uuid)
    else:
      demographics_question = DemographicsModel.objects.all()
      questionTwo = DemographicsTwoModel.objects.all()
      out = {'questionsOne': demographics_question,'questionTwo': questionTwo} 
      return render(request, "Assessment/assessment/Demographics.html", out)

def demographicsAnswerOne(request):
    if request.method == 'POST':
        studentAnsOne = request.POST['studentAnsOne']
        studentUUID = request.POST['studentUUID']
        Player.objects.filter(uuid=studentUUID).update(demographics=studentAnsOne)
        message = 'Pre assessment save'
        return HttpResponse(message)

def demographicsAnswerTwo(request):
    if request.method == 'POST':
        studentAnsTwo = request.POST['studentAnsTwo']
        studentUUID = request.POST['studentUUID']
        newAnswer = []

        models = Player.objects.filter(uuid=studentUUID).first()
        ans = models.demographics
        newAnswer.append(ans)
        newAnswer.append(studentAnsTwo)
        new_string = ''.join(str(x) for x in newAnswer)
        Player.objects.filter(uuid=studentUUID).update(demographics=new_string)

        out = {'stud_uuid': studentUUID}
        return JsonResponse(out)

#AJAX function to save student answer key on personality test database 
def personalityTestAnswer(request):
    if request.method == 'POST':
        studentAns1 = request.POST['studentAns']
        studentUUID = request.POST['studentUUID']
        Player.objects.filter(uuid=studentUUID).update(personality_test=studentAns1)
        message = 'Personality Test Save!'
        return HttpResponse(message)


def createAccountAjax(request):
    if request.method == 'POST':
        userName = request.POST['user_name']
        usersSurname = request.POST['users_surname']
        section = request.POST['section']
        gender = request.POST['user_gender']

        age = request.POST['user_age']
        age = int(age)

        userName = userName.capitalize()
        usersSurname = usersSurname.capitalize()
        section = section.capitalize()

        # Check if the user name is already use
        if Player.objects.filter(username=userName).exists():
            message = f'{userName} already exist. Please try another username'
            return HttpResponse(message)
        else:
            models = Player(username=userName, surname=usersSurname, age=age, gender=gender, section=section)
            models.save()
            user_uuid = models.uuid
            user_uuid = str(user_uuid)
            request.session['uuid'] = user_uuid
            message = user_uuid
            return HttpResponse(message)

def createAccount(request):
    try:
        session = request.session._get_or_create_session_key()
        user_key = Player.objects.get(user_session=session)
        if user_key.user_session != None:
            sessionTwo = request.session._get_or_create_session_key()
            user_key = Player.objects.get(user_session=sessionTwo)
            # if a user is already have a session id it will redirect to main menu urls. 
            return redirect('Assessment:mainMenu', uuid=user_key.uuid)
    except:
        session = None
        return render(request, "Assessment/createAccount.html")     

        

def loginPage(request):
    sample = ResearchStatus.objects.all()
    out = {
        "check":sample
    }
    return render(request,"Assessment/login.html", out)


def multiplayer_signIn(request):
    return render(request,"Assessment/signIn.html")

def multi_signIn_ajax(request):
    if request.method == 'POST':
        signIn_user = request.POST['signIn_user']
        signIn_user = signIn_user.capitalize()

        user_model =  Player.objects.filter(username=signIn_user)
        if user_model.exists():
            user_get_credentials = Player.objects.filter(username=signIn_user).first()
            credential_id = user_get_credentials.uuid
            out = {
                'credential': credential_id
            }
            return JsonResponse(out)
        else:
            message = "Please check your username!"

        return HttpResponse(message)

def pre_test(request, uuid):
    user_uuid = uuid
    request.session['uuid'] = user_uuid
    modelPretest = PreTest.objects.all()

    out = {
        "pretest": modelPretest
    }

    return render(request,"Assessment/PreTestAndPostTest/preTest.html", out)

def pre_test_answer(request):
    if request.method == 'POST':
        pretestAnswers = request.POST['pretestAnswers']
        pretestScore = request.POST['pretestScore']
        studentUUID = request.POST['studentUUID']
        Player.objects.filter(uuid=studentUUID).update(pre_test_score=pretestScore, pre_test_answer=pretestAnswers)


        message = "Nice"
        return HttpResponse(message)

# In every group there must be an uqual room name
def create_room_for_every_group(user):
    group_list = Group.objects.all()

    for i in range(len(group_list)):
        if not chk_has_room(group_list[i].name):
            new_room = Room.objects.create(
                room_name = group_list[i].name,
                group_name = group_list[i],
                password = "",
                is_research = True,
                # players = user.username if user.group == group_list[i] else "",
            )
            new_room.save()

def chk_has_room(group):
    room_list = Room.objects.all()
    for i in range(len(room_list)):
        if room_list[i].room_name == group:
            return True 
    return False

def auto_assign_room_if_has_group(user, group):
    # print("Group: " + group)
    if group != None:
        room = Room.objects.get(group_name=group)
        if user.username not in room.players:
            player_list = room.players
            player_list = player_list + ", " + user.username
            room.players= player_list
            room.save()
        

# Checks if in research mode
# ResearchStatus.object().research_mode

    

Assessment/templates/Assessment/assessment/Demographics.html
{% extends 'revise_multiplayer/multiPlayerBase.html' %}

{% block title %}Demographics{% endblock %}

{% block content %}

<div class="demographics-container">
    <div class="top-demo-titile" id="DemoTitle">
        <p class="main-title-q">Demographics Questionnaire</p>
        <p class="title" id="demo-title">I.	Read the following questions, and place a checkmark ( ) on the checkbox of your answer. </p>
        <p class="title-2" id="demo-ti-two">Basahin ang sumusunod na tanong, at lagyan ng tsek ( ) ang checkbox ng iyong sagot.</p>
    </div>
    <div class="form-demo-con">
    <form action="" method="POST" id="demo-form" autocomplete="off">
        {% csrf_token %}
        <ol class="oderList likert">
            {% for i in questionsOne %}
            <li class="demo-label questionsOne">{{i.question_part_one}}</li><span class="demo-tagalog">{{i.question_part_one_tagalog}}</span>
            <p class="Onecurrent-id">choiceOne-{{i.id}}</p>
            <label for="y-{{i.id}}" class="label_radio">
                <input type="radio" id="y-{{i.id}}" class="radio-two" value="Yes" name="choiceOne-{{i.id}}" required="required">
                <div class="radio_input"></div>
                Yes/Oo
            </label>

            <label for="n-{{i.id}}" class="label_radio">
                <input type="radio" id="n-{{i.id}}" class="radio-two" value="No" name="choiceOne-{{i.id}}" required="required">
                <div class="radio_input"></div>
                No/Hindi
            </label>
            {% endfor %}
        </ol>
        <div id="unorder" class="unorderList">
            <ul>
                {% for i in questionTwo %}
                <h4 name="questions" class="questions questionsTwo">{{i.question_part_two}}</h4><span class="demo-tagalog">{{i.question_part_two_tagalog}}</span>
                <p class="current-id">choice-{{i.id}}</p>
                <ul class='likert'>
                    <span class="line"></span>
                    <li>
                        <label for="sa-{{i.id}}"  class="label_radio">
                            <input type="radio" id="sa-{{i.id}}" class="radio-two" value="Agree strongly" name="choice-{{i.id}}" >
                            <div class="radio_input"></div>
                            Agree strongly
                        </label> 
                    </li>
                    <li>
                        <label for="a-{{i.id}}"class="label_radio">
                            <input type="radio" id="a-{{i.id}}" class="radio-two" value="Agree a little" name="choice-{{i.id}}" >
                            <div class="radio_input"></div>
                            Agree a little
                        </label>   
                    </li>
                    
                    <li>
                        <label for="n1-{{i.id}}"class="label_radio"> 
                            <input type="radio" id="n1-{{i.id}}"class="radio-two" value="Neutral" name="choice-{{i.id}}" >
                            <div class="radio_input"></div>
                            Neutral
                        </label>
                    </li>
                    <li>
                        <label for="d-{{i.id}}"class="label_radio"> 
                            <input type="radio" id="d-{{i.id}}"class="radio-two" value="Disagree a little" name="choice-{{i.id}}" >
                            <div class="radio_input"></div>
                            Disagree a little
                        </label>
                    </li>
                    <li>
                        <label for="sd-{{i.id}}"class="label_radio">  
                            <input type="radio" id="sd-{{i.id}}"class="radio-two" value="Disagree Strongly" name="choice-{{i.id}}" >
                            <div class="radio_input"></div>
                            Disagree Strongly
                        </label>
                    </li>
                </ul>
                {% endfor %}
            </ul>
            
        </div>
        
        
         <button type="submit" id="submit" name="demoSub" class="btn btn-primary demograp">continue</button>
    </form>
    </div>
   
</div>

{% endblock %}
{% block scripts %}

<script type="text/javascript">
    var user_uuid= "{{ request.session.uuid }}"

    var project = document.querySelector('#DemoTitle');
    var titleOne = document.querySelector('#demo-title');
    var titleTwo = document.querySelector('#demo-ti-two');

    const btnSubmit = document.querySelector(".demograp");
    var count = 0

    function questions(str){
      let questions_array = []
      
      for(i=0;i<str.length;i++){
        let quest_idOne = str[i].innerHTML;
        questions_array.push(quest_idOne);
      }

      return questions_array
    }

    // ==================================================
    let questionsAOne = document.getElementsByClassName("questionsOne");
    let questionsArrayOne = questions(questionsAOne)
  

   
   let current_idOne = document.getElementsByClassName("Onecurrent-id");
   let classNameOne = questions(current_idOne)
   
    let resultsOne = [];
   
//    ================================== Two questions ================
    let questionsA = document.getElementsByClassName("questionsTwo");
    let questionsArray = questions(questionsA)
    var arrLength = questionsArray.length;

   
   let current_id = document.getElementsByClassName("current-id");
   let className = questions(current_id)
   let results = [];
    
    // ===================================================
    var counter_two = 0;
    $("#demo-form").on("submit", function(e){
        ++count
        e.preventDefault();
        if(btnSubmit.classList.contains('newClassName')) {
            results = className.map(function(el){

                let answerTwo = document.querySelector("input[name='" + el+ "']:checked");
                
                if(answerTwo != null){
                    answerTwo= document.querySelector("input[name='" + el + "']:checked").value;
                    return answerTwo
                }else{
                    ++counter_two;
                    if(counter_two > 1){
                        if (counter_two === arrLength){
                            counter_two = 0;
                        }
                    }else{
                        Swal.fire({
					        position: 'center',
                            icon: 'warning',
                            title: 'Please check your input',
                            // showConfirmButton: false,
                            // timer: 1500
				        })
                    }
                }


             });

            var counting = 0; 
            var pre_assess_dictionary = {}
            for (let i = 0; i < questionsArray.length; i++) {
                // console.log(results[i],"<<<<")
                pre_assess_dictionary[questionsArray[i]] = results[i];
                if(typeof results[i] === "undefined"){
                    ++counting;
                }else{
                    counting = 0;
                }
            }
            
            if(counting < 1){
                // ============================= Ajax==============
                var url = '{% url "Assessment:demoTwoAnswer" %}'
                $.ajax({
                    type:'POST',
                    url:url,
                    data:{
                        studentAnsTwo: JSON.stringify(pre_assess_dictionary),
                        studentUUID: user_uuid,
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                    },
                    success:function(data){
                        console.log("save 2")
                        redirect_url = '/personality-test/'+data.stud_uuid;
                        window.location.replace(redirect_url);
                    },
                    error : function () {
                        alert("Error Ajax Two");
                    }
                });
            }

        }else{

            project.style.opacity = 0;
            setTimeout(function(){ 
                titleOne.innerHTML = "II. Place a checkmark ( ) on the box that represents your agreement or disagreement toward the following statements. ";
                titleTwo.innerHTML = "Lagyan ng tsek ( ) ang kahon na magpapakita ng iyong pagsang-ayon o di pagsang-ayon sa mga sumusunod na pangungusap.";
                project.style.opacity = 1;
            },500);

            const ol = document.querySelector(".oderList");
            ol.classList.toggle("orderDisplay");

            var display_ul = document.getElementById("unorder");
            display_ul.classList.remove("unorderList");

            resultsOne = classNameOne.map(function(el){
                let answer = document.querySelector("input[name='" + el + "']:checked").value;
                return answer
             });

            var pre_assess_dictionaryOne = {};
           
            for (let i = 0; i < questionsArrayOne.length; i++) {
                pre_assess_dictionaryOne[questionsArrayOne[i]] = resultsOne[i];
                
            }


            btnSubmit.classList.toggle("newClassName");

            // ============================= Ajax==============
            var url = '{% url "Assessment:demoOneAnswer" %}'
            $.ajax({
                type:'POST',
                url:url,
                data:{
                    studentAnsOne: JSON.stringify(pre_assess_dictionaryOne),
                    studentUUID: user_uuid,
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                },
                success:function(data){
                    console.log("save 1")
                },
                error : function () {
                    alert("Error Ajax");
                }
		    });

        }
    });
</script>

{% endblock %}

Assessment/templates/Assessment/assessment/personalityTest.html
{% extends 'revise_multiplayer/multiPlayerBase.html' %}

{% block title %}Personality Test{% endblock %}

{% block content %}
<div class="conPreAss">
    
    <div class="assessment-title">
        <p class="main-title-q">Personality Test</p>
    </div>

<div class="overall-con">
    <p class="description">Here are some statements that may or may not describe what you are like.  In the blank next to each statement, click your response or answer that shows how much you agree or disagree that it describes you.<br><br> For example, do you agree that you are someone who is bossy?  Click agree strongly if you agree strongly, agree a little if you agree a little, neutral if you neither agree nor disagree, disagree a little if you disagree a little, or disagree strongly if you disagree strongly. Ask if you don’t know what a word means!</p>
    <div class="assessment-container">
        <form action="" method="POST" id="assessment-form" autocomplete="off">
        {% csrf_token %}
            
            {% for i in assess %}
    
                 <h4 name="questions" class="questions">{{ forloop.counter }}.&ensp;{{i.questions}}</h4>

                <p class="current-id">choice-{{i.id}}</p>
                <ol class='likert'>
                    <span class="line"></span>
                    <li>
                      <input type="radio" id="sa-{{i.id}}" value="Agree strongly" name="choice-{{i.id}}" required="required">
                      <label for="sa-{{i.id}}">Agree strongly</label>
                    </li>
                    <li>
                      <input type="radio" id="a-{{i.id}}" value="Agree a little" name="choice-{{i.id}}" required="required">
                      <label for="a-{{i.id}}">Agree a little</label>
                      
                    </li>
                    <li>
                      <input type="radio" id="n-{{i.id}}" value="Neutral" name="choice-{{i.id}}"  required="required" >
                      <label for="n-{{i.id}}">Neutral</label>
                    </li>
                    <li>
                      <input type="radio" id="d-{{i.id}}" value="Disagree a little" name="choice-{{i.id}}" required="required">
                      <label for="d-{{i.id}}">Disagree a little</label>
                    </li>
                    <li>
                      <input type="radio" id="sd-{{i.id}}" value="Disagree Strongly" name="choice-{{i.id}}" required="required">
                      <label for="sd-{{i.id}}">Disagree Strongly</label>
                    </li>
                  </ol>

            {% endfor %}

            <button type="submit" id="submit" name="preAssessment" class="btn btn-primary preSub">Submit</button>
        </form>
    </div>
</div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">

  
    var user_uuid= "{{ request.session.uuid }}"

    let questionsA = document.getElementsByClassName("questions");
    let questionsArray = []
    for(i=0;i<questionsA.length;i++){
        let quest_id = questionsA[i].innerHTML;
        questionsArray.push(quest_id);
   }



   let current_id = document.getElementsByClassName("current-id");
   let className = [];
   let id; 
   for(i=0;i<current_id.length;i++){
        id = current_id[i].innerHTML;
        className.push(id);
   }
   
    let results = [];
 

    
    $("#assessment-form").on("submit", function(e){
	e.preventDefault();

        results = className.map(function(el){
            return document.querySelector("input[name='" + el + "']:checked").value;
        });

        var pre_assess_dictionary = {}
        for (let i = 0; i < questionsArray.length; i++) {
            pre_assess_dictionary[questionsArray[i]] = results[i];
        }

        var url = '{% url "Assessment:preAnswer" %}'
        $.ajax({
			type:'POST',
			url:url,
			data:{
                studentAns: JSON.stringify(pre_assess_dictionary),
                studentUUID: user_uuid,
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
			},
			success:function(data){
                Swal.fire({
					position: 'center',
                    icon: 'success',
                    title: data,
                    showConfirmButton: false,
                    timer: 1500
				})

                // sleep time expects milliseconds
                function sleep (time) {
                    return new Promise((resolve) => setTimeout(resolve, time));
                }

                // Usage!
                sleep(1200).then(() => {
                    // Do something after the sleep!
                    redirect_url = '/pre-test/'+user_uuid;
                    window.location.replace(redirect_url);
                });
                
                
			},
            error : function () {
                alert("Error Ajax");
            }
		});
		
	});
    


    
</script>
{% endblock %}