Assessment/urls.py
from django.urls import path
from . import views

app_name = 'Assessment'

urlpatterns = [
    path("ibigkas-menu/<uuid>/", views.mainPage, name="mainMenu"),

    path("", views.loginPage, name="login_page"),

    path("signIn", views.multiplayer_signIn, name="SignIn_multi"),
    path("create-account/", views.createAccount, name="createAccount"),
    
    # Assessment urls
    path("personality-test/<uuid>/", views.personalityTest, name="personality_test"),
    path("demographics/<uuid>/", views.demographicsQuestion, name="demographics"),

    path("pre-test/<uuid>/", views.pre_test, name="pre_test"),

    # AJAX URL PATH
    path("pre_test_ans/", views.pre_test_answer, name="pre_test_ans"),
    path("signIn_multi/", views.multi_signIn_ajax, name="multi_signIn"),
    path("demo_ansOne/", views.demographicsAnswerOne, name="demoOneAnswer"),
    path("demo_ansTwo/", views.demographicsAnswerTwo, name="demoTwoAnswer"),
    path("pre_assessment_ans/", views.personalityTestAnswer, name="preAnswer"),
    path("createAccoutAjax/", views.createAccountAjax, name="createAjax"),




]

ibigkas_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('jet/', include('jet.urls', 'jet')), 
    path('admin/', admin.site.urls),
    path('singleplayer/', include("singlePlayer.urls")),
    path('multiplayer/', include("revise_multiplayer.urls")),
    path('', include("Assessment.urls")),
]


admin.site.index_title = "Ibigkas"
admin.site.site_header = "Ibigkas Web Application Admin"
admin.site.site_title = "Ibigkas Admin"


# snake_case python 
# camelCase JS 
# kebab-case CSS  

singlePlayer/urls.py
from django.urls import path
from . import views 

app_name = 'singlePlayer'

urlpatterns = [ 
    path("menu-single-player/<uuid>/", views.singlePlayerMenu, name="singlePlayerMenu"),
    path("settings/<uuid>/", views.singlePlayerSettings, name="singlePlayerSettings"),
    path("how-to-play/", views.singlePlayerHowToPlay, name="HowToPlay"),
    path("game-play/<pk>/", views.singlePlayerGamePlay, name="gameplay"),

    # Ajax
    path("singlePlayerSettingsAjax/", views.singlePlayerSettingsAjax, name="singlePlayerSettingsAjax"),
    path("userGameResultsAjax/", views.userGameResults, name="userGameResultsAjax"),

]

singlePlayer/models.py
from tabnanny import verbose
from django.db import models
from Assessment.models import *
# Create your models here.

class GameSetting(models.Model):
  setting_id = models.BigAutoField(primary_key=True, verbose_name="ID")
  player = models.ForeignKey(Player, on_delete=models.CASCADE, verbose_name="Player")
  arithmetic = models.CharField(max_length=250, verbose_name='Arithmetic')
  difficulty = models.CharField(max_length=250, verbose_name='Difficulty')
  speed = models.CharField(max_length=250, verbose_name='Speed')
  lvl = models.CharField(max_length=250, verbose_name='lvl')

singlePlayer/forms.py
from django import forms

class SettingsForm(forms.Form):
  arithmetic = forms.CharField(label='arithmetic', max_length=100)
  difficulty = forms.CharField(label='difficulty', max_length=100)
  speed = forms.CharField(label='speed', max_length=100)
  lvl = forms.CharField(label='lvl', max_length=100)

singlePlayer/views.py
# Django Imports
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect


from django.views.decorators.csrf import csrf_exempt


# External Imports 
import json 

# Internal Imports
from . import utility as utils 
from . import filter_question_data as filter_qa
from Assessment.models import * 
from singlePlayer.models import *
from .forms import SettingsForm

def singlePlayerMenu(request, uuid):
  user_uuid = uuid
  request.session['uuid'] = user_uuid
  Player.objects.filter(uuid=uuid).update(player_mode="SinglePlayer")
  return render(request, "singlePlayer/singlePlayerMenu.html")

def singlePlayerSettings(request, uuid):
  user_uuid = uuid
  request.session['uuid'] = user_uuid
  return render(request, "singlePlayer/gameSettings.html")


def singlePlayerSettingsAjax(request):
  if request.method == 'POST':
    arithmeticResults = request.POST['arithmeticResults']
    difficultyResults = request.POST['difficultyResults']
    year_level = request.POST['year_level']
    speed = request.POST['speed']
    studentUUID = request.POST['studentUUID']

    def newFormat(s):
      s = s.translate({ord('['): None})
      s = s.translate({ord(']'): None})
      s = s.translate({ord('"'): None})
      return s
    
    arithmeticResults = newFormat(arithmeticResults)
    difficultyResults = newFormat(difficultyResults)
    
    if speed == "medium-two":
      speed = "medium"
    elif speed == "Untimed":
      speed = "untimed"

    settings = {
        'arithmetic' : arithmeticResults,
        'lvl' : year_level,
        'speed' : speed,
        'difficulty' : difficultyResults
    }

    player_name = Player.objects.get(uuid=studentUUID)
      
    create_setting = GameSetting(
        player = player_name,
        arithmetic = settings['arithmetic'],
        difficulty = settings['difficulty'],
        speed = settings['speed'],
        lvl = settings['lvl']
    )
    create_setting.save()
    pk = create_setting.setting_id
    return HttpResponse(pk)

@csrf_exempt
def userGameResults(request):
  game_history_list = []
  game_correct = []
  game_wrong = []
  game_total = []
  game_speed = []

  if request.method == 'POST':
    game_history = request.POST['game_history']
    correct_answer = request.POST['correct_answer']
    wrong_answer = request.POST['wrong_answer']
    total_questions = request.POST['total_questions']
    speed = request.POST['speed']
    studentUUID = request.POST['studentUUID']
    models = Player.objects.filter(uuid=studentUUID).first()

    # print(s.translate({ord(i): None for i in 'abc'}))
    game_history = game_history.translate({ord('{'):None, ord('}'):None, ord('"'):None})

    # use append for single value
    # extend for multiple values

    models_game_answer_history = models.game_answer_history
    models_correct = models.correct_answers
    models_wrong = models.wrong_answers
    models_total = models.total_questions
    models_speed = models.speed

    def list_to_string(name):
      list_name = ' '.join(map(str, name))
      return list_name

    if models_game_answer_history != '':
      game_history_list.append(models_game_answer_history)
      game_correct.append(models_correct)
      game_wrong.append(models_wrong)
      game_total.append(models_total)
      game_speed.append(models_speed)

    game_history_list.append(game_history)
    game_correct.append(correct_answer)
    game_wrong.append(wrong_answer)
    game_total.append(total_questions)
    game_speed.append(speed)

   
    Player.objects.filter(uuid=studentUUID).update(game_answer_history=list_to_string(game_history_list), total_questions=list_to_string(game_total),
    correct_answers = list_to_string(game_correct), wrong_answers = list_to_string(game_wrong), speed = list_to_string(game_speed)
    )
    return HttpResponse('Data save!')


    
def singlePlayerHowToPlay(request):
  return render(request, "singlePlayer/howToPlay.html")




def singlePlayerGamePlay(request, pk): 
  setting_entry = GameSetting.objects.get(setting_id = pk)
  settings = utils.user_input(setting_entry)

  data = filter_qa.filter_question_dataset(settings)
  game_round_state = utils.init_game_round_variables()

  out = {
    "settings": settings,  
    "json_settings": json.dumps(settings),
    "json_game_round_state": json.dumps(game_round_state),
    "json_data" : json.dumps(data) 
  }
  return render(request, "singlePlayer/gameplay.html", out)

singlePlayer/templates/singlePlayer/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <!-- favicon  -->
    <link rel="shortcut icon" href="{% static 'Assessment/img/logo.png' %}">
     <!-- ----- -->
    <link rel="stylesheet" href="{% static 'singlePlayer/styles/bootstrap.css' %}"/>
	  <link rel="stylesheet" href="{% static 'singlePlayer/styles/gameplay.css'%}?{% now "U" %}"">
	  <link rel="stylesheet" href="{% static 'singlePlayer/styles/singlePlayerHowtoPlay.css'%}?{% now "U" %}"">
	  <link rel="stylesheet" href="{% static 'singlePlayer/styles/singlePlayerMenu.css'%}?{% now "U" %}"">
	  <link rel="stylesheet" href="{% static 'singlePlayer/styles/singlePlayerSettings.css'%}?{% now "U" %}"">
  </head>
  <body oncopy="return false" oncut="return false" onpaste="return false">

	<div class="main">
		<div class="second-base" id="second-base_id">
    		{% block content %} {% endblock %}
		</div>
	</div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    {% block scripts %} {% endblock %}
  </body>
</html>

singlePlayer/templates/singlePlayer/gameSettings.html
{% extends 'singlePlayer/base.html' %} {% block title %}Settings{% endblock %}
{% block content %}
{% load static %}
<form method="POST" class="needs-validation" id="player_settings">
  {% csrf_token %}
  <div class="second-valid">
    <h3 class="menu-title top-title arithmetic-label" style="display:inline; padding-left:20px;">Arithmetic:</h3>
    <h3 class="menu-title top-title difficulty-label" style="display:inline; padding-left:70px;">Difficulty:</h3>

    <div class="settings-center">
      
      <div class="select-box">
        <div class="over">
          <div class="options-container">
            <div class="option">

              <input type="radio" class="radio" id="addition" name="arithmetic" value="addition"/>
              <label for="addition">Addition</label>
            </div>
            <div class="option">
              <input type="radio" class="radio" id="subtraction" name="arithmetic" value="subtraction"/>
              <label for="subtraction">Subtraction</label>
            </div>
            <div class="option">
              <input type="radio" class="radio" id="multiPlayer" name="arithmetic" value="multiplication"/>
              <label for="multiPlayer">Multiplication</label>
            </div>
            <div class="option">
              <input type="radio" class="radio" id="division" name="arithmetic" value="division"/>

              <label for="division">Division</label>
            </div>
          </div>
        </div>
        <div class="selected" id="arithmetic-selection">
          <p id="arithmetic-selectionTwo">Addition</p>
          <div class="arrow colored"></div>
        </div>
      </div>

      <div class="select-box-two">
        <div class="options-container-two">
          <div class="option-two">
            <input type="radio" class="radio" id="very_easy" name="difficulty" value="very_easy"/>
            <label for="very_easy">VERY EASY</label>
          </div>
          <div class="option-two">
            <input type="radio" class="radio" id="easy" name="difficulty" value="easy"/>
            <label for="easy">EASY</label>
          </div>
          <div class="option-two">
            <input type="radio" class="radio" id="medium" name="difficulty" value="medium"/>
            <label for="medium">MEDIUM</label>
          </div>
          <div class="option-two">
            <input type="radio" class="radio" id="hard" name="difficulty" value="hard"/>
            <label for="hard">HARD</label>
          </div>
          <div class="option-two">
            <input type="radio" class="radio" id="very_hard" name="difficulty" value="very_hard"/>
            <label for="very_hard">VERY HARD</label>
          </div>
          </div>

          <div class="selected-two" id="difficulty-selection">
            <p id="difficulty-selectionTwo">VERY EASY</p>
          <div class="arrow colored"></div>
        </div>
      </div>
      
      

    </div>

    <div class="select-box-three">
      <div id="error"></div>
      <h3 class="menu-title">Year Level:</h3>
        <div class="options-container-three">
          <div class="option-three">
            <label for="lvl1" class="label_radio">
              <input type="radio" class="radio-two" id="lvl1" name="lvl" value="lvl1" required/>
              <div class="radio_input"></div>
              Grade 1
            </label>
          </div>
          <div class="option-three">
            <label for="lvl2" class="label_radio">
              <input type="radio" class="radio-two" id="lvl2" name="lvl" value="lvl2"/>
              <div class="radio_input"></div>
              Grade 2
            </label>
          </div>
          <div class="option-three">
            <label for="lvl3" class="label_radio">
              <input type="radio" class="radio-two" id="lvl3" name="lvl" value="lvl3"/>
              <div class="radio_input"></div>
              Grade 3
            </label>
          </div>
        </div>

       
    </div>

    <div class="speed-container sing1Player">
      <div id="errortwo"></div>
      <h3 class="menu-title">Speed:</h3>
      <div class="speed-settings">
        <div>
          <label for="Untimed" class="label_radio">
            <input type="radio" class="radio-two" id="Untimed" name="speed" value="Untimed" required="required"/>
            <div class="radio_input"></div>
            Untimed
          </label><br />
          <label for="very_slow" class="label_radio">
            <input type="radio" class="radio-two" id="very_slow" name="speed" value="very_slow" />
            <div class="radio_input"></div>
            Very Slow
          </label><br />
          <label for="slow" class="label_radio">
            <input type="radio" class="radio-two" id="slow" name="speed" value="slow" />
            <div class="radio_input"></div>
            Slow
          </label><br />
        </div>
        <dir>
          <label for="medium-two" class="label_radio">
            <input type="radio" class="radio-two" id="medium-two" name="speed" value="medium-two" />
            <div class="radio_input"></div>
            Medium
          </label><br />

          <label for="fast1" class="label_radio">
            <input type="radio" class="radio-two" id="fast1" name="speed" value="fast" />
            <div class="radio_input"></div>
            Fast
          </label><br />
          <label for="very_fast" class="label_radio">
            <input type="radio" class="radio-two" id="very_fast" name="speed" value="very_fast" />
            <div class="radio_input"></div>
            Very Fast
          </label><br />
        </dir> 
      </div>
    </div>

    <div class="button-container">
      <button onclick="back_ToMenu()" type="button" name="back" class="btn btn-primary">back</button>
      <button type="submit" name="submit" class="btn btn-primary" id="start-but">start</button>  
    </div>

  </div>

</form>

{% endblock %} 
{% block scripts %} 
<script type="text/javascript">
  var user_uuid= "{{ request.session.uuid }}";

  const selected = document.querySelector(".selected");
  const options_Container = document.querySelector(".options-container")
  const optionList = document.querySelectorAll(".option")

  const selected_two = document.querySelector(".selected-two");
  const options_Container_two = document.querySelector(".options-container-two")
  const optionList_two = document.querySelectorAll(".option-two")

  selected.addEventListener("click",() =>{
    options_Container.classList.toggle("active");
    options_Container_two.classList.remove("active-two");
  })


  optionList.forEach(o => {
    o.addEventListener("click", () => {
    selected.innerHTML = o.querySelector("label").innerHTML;
      options_Container.classList.remove("active");      
    })
  })

  //==================================================

  selected_two.addEventListener("click",() =>{
    options_Container_two.classList.toggle("active-two");
    options_Container.classList.remove("active");      
  })

  optionList_two.forEach(o => {
    o.addEventListener("click", () => {
      selected_two.innerHTML = o.querySelector("label").innerHTML;
      options_Container_two.classList.remove("active-two");
    });
  });


  
  // Ajax part

  let arithmeticResults = [];
  let difficultyResults = [];

  const errorMessage =  document.querySelector("#error");
  const errorMessagetwo =  document.querySelector("#errortwo");
  var errorCounter = 0;
  var errorCounterTwo = 0;


  $("#start-but").on("click", function(e){
    e.preventDefault();

    
    let arithmeticSel = document.querySelector('#arithmetic-selection');
    let arithmeticSelTwo = document.querySelector('#arithmetic-selectionTwo');    

    if(arithmeticSelTwo != null){
        arithmeticSelTwo = arithmeticSelTwo.innerHTML;
        arithmeticSelTwo = arithmeticSelTwo.toLowerCase();

        arithmeticResults.push(arithmeticSelTwo);

        if(arithmeticResults.length > 1){
            arithmeticResults.shift();
        }
    }else{

      arithmeticSel = arithmeticSel.innerHTML;
      arithmeticSel = arithmeticSel.toLowerCase();
      arithmeticResults.push(arithmeticSel);

      if(arithmeticResults.length > 1){
          arithmeticResults.shift();
      }
    }    



    let difficultySel = document.querySelector('#difficulty-selection');
    let difficultySelTwo = document.querySelector('#difficulty-selectionTwo');
    

    if(difficultySelTwo != null){
      difficultyResults.push("very_easy");

      if(difficultyResults.length > 1){
            // shift() --> to remove first index in array
            difficultyResults.shift();
        }
    }else{
      difficultySel = difficultySel.innerHTML;
      difficultySel = difficultySel.toLowerCase();

      if(difficultySel === "very easy"){
        difficultySel = "very_easy";
        difficultyResults.push(difficultySel);
      
        if(difficultyResults.length > 1){
            difficultyResults.shift();
        }

      }else if(difficultySel === "very hard"){
        difficultySel = "very_hard";
        difficultyResults.push(difficultySel);

        if(difficultyResults.length > 1){
            difficultyResults.shift();
        }
      }else{
        difficultyResults.push(difficultySel);
        if(difficultyResults.length > 1){
            difficultyResults.shift();
        }
      }
    }
    

    let year_level = document.querySelector('input[name="lvl"]:checked');
    let speed_click = document.querySelector('input[name="speed"]:checked');


    if(year_level != null){
      year_level = year_level.value;
      errorCounterTwo = 0
      errorMessage.innerHTML = "";
    }else{
      ++errorCounterTwo;
      let audio = new Audio("{% static 'Assessment/music/warning.wav' %}");
      audio.play()
      errorMessage.innerHTML = 'Please select year level !';
    }

    if(speed_click != null){
      speed_click = speed_click.value;
      errorCounter = 0
      errorMessagetwo.innerHTML = "";
    }else{
      ++errorCounter;
      let audio = new Audio("{% static 'Assessment/music/warning.wav' %}");
      audio.play()
      errorMessagetwo.innerHTML = 'Please select year speed !';
    }

    
    var url = '{% url "singlePlayer:singlePlayerSettingsAjax" %}'

    if(errorCounter === 0 && errorCounterTwo === 0){
      $.ajax({ 
        type:'POST',
          url:url,
          data:{
              arithmeticResults: JSON.stringify(arithmeticResults),
              difficultyResults: JSON.stringify(difficultyResults),
              year_level: year_level,
              speed:speed_click,
              studentUUID: user_uuid,
              csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
          },
          success:function(data){
            let audio = new Audio("{% static 'Assessment/music/IBM_ui_Confirm.wav' %}");
            audio.play()
            setTimeout(function(){ 
                redirect_url = '/singleplayer/game-play/'+data;
                window.location.replace(redirect_url);
            }, 400);
          },
          error : function () {
              alert("Error Ajax");
          }
      });

    }
    

  });

	



</script>

<script>
  function back_ToMenu(){
      let audio = new Audio("{% static 'Assessment/music/IBM_ui_Back.wav' %}");
      audio.play()
      setTimeout(function(){ 
        window.location.replace('/singleplayer/menu-single-player/'+ user_uuid);
      }, 400);
  }
</script>

{% endblock %}

singlePlayer/templates/singlePlayer/howToPlay.html
{% extends 'singlePlayer/base.html' %} 
{% block title %} 
how to play
{% endblock %} 
{% load static %}

{% block content %}
<div class="how-to-play-container">
    <div class="headings">
        <h4>Parts of the game:</h4>
    </div>
    <div class="mini-game-container">
        <div class="mini-game-layout">
            <div class="top-border"></div>

            <div class="score">
                <p>Score: 0</p>
            </div>

            <div class="game-problem">
                <p class="num4">4</p>
                <div class="problem">
                    <p class="operator">+</p>
                    <p>2</p>
                </div>
            </div>

            <div class="bottom-border"></div>

            <div class="game-choices">
                <p>0</p>
                <p>6</p>
                <p>10</p>
            </div>
        </div>
        <div class="cir1">
            <p>Target</p>
         <img src="{% static 'Assessment/img/tutor/Circle.png' %}" alt="">
        </div>
        <div class="cir2">
            <p>Buttons</p>
            <img src="{% static 'Assessment/img/tutor/Circle.png' %}" alt="">
        </div>
        <div class="hand">
            <img src="{% static 'Assessment/img/tutor/Hand.png' %}" alt="">
        </div>
    </div>
    <div class="button-container">
        <button type="button" name="back" class="btn btn-primary">back</button>
        <button type="submit" name="exit" class="btn btn-primary exit">x</button>  
        <button type="submit" name="start" class="btn btn-primary">next</button>  
    </div>
</div>
{% endblock %}

singlePlayer/templates/singlePlayer/singlePlayerMenu.html
{% extends 'singlePlayer/base.html' %} 
{% block title %} 
Ibigkas Math! Singleplayer 
{% endblock %} 
{% load static %}
{% block content %}

<form method="POST" action="">
{% csrf_token %}
<div class="menu-options">
  <h1>Single Player:</h1>
        <button onclick="start_game()" type="button" name="host-game" class="btn btn-primary">start game</button>
        <button type="button" name="how-to-play" class="btn btn-primary">how to play</button>
</div>

<button onclick="backMain()" type="button" class="btn btn-primary menu-back">back</button>
</form>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    var user_uuid= "{{ request.session.uuid }}"
    function start_game(){
        let audio = new Audio("{% static 'Assessment/music/IBM_ui_Confirm.wav' %}");
        audio.play()
        setTimeout(function(){ 
            window.location.replace('/singleplayer/settings/'+ user_uuid);
        }, 400);
    }
    function backMain(){
        let audio = new Audio("{% static 'Assessment/music/IBM_ui_Back.wav' %}");
        audio.play()
        setTimeout(function(){ 
            window.location.replace('/ibigkas-menu/'+ user_uuid);
        }, 400);
    }
</script>
{% endblock %}